---
abstract: 'Callbacks for changes to a packages symbol table '
author:
  - 'Scott McWhirter <konobi@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-StashHook
no_index:
  directory:
    - inc
    - t
requires:
  Variable::Magic: 0
version: 0.01_001
